# Generated by Django 5.2.17 on 2026-08-16 19:49

import apps.listings.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم (عربي)')),
                ('name_tr', models.CharField(blank=True, max_length=120, verbose_name='الاسم (تركي)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنكليزي)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'سبب رفض',
                'verbose_name_plural': 'أسباب الرفض',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='العنوان')),
                ('description', models.TextField(max_length=4000, verbose_name='الوصف')),
                ('price', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='السعر')),
                ('condition', models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل')], default='used', max_length=8, verbose_name='الحالة')),
                ('status', models.CharField(choices=[('draft', 'مسودّة'), ('pending', 'قيد المراجعة'), ('published', 'منشور'), ('rejected', 'مرفوض'), ('expired', 'منتهٍ'), ('suspended', 'موقوف'), ('deleted', 'محذوف')], db_index=True, default='pending', max_length=12, verbose_name='حالة الإعلان')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='مميّز')),
                ('featured_until', models.DateTimeField(blank=True, null=True, verbose_name='مميّز حتى')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='المشاهدات')),
                ('contacts_count', models.PositiveIntegerField(default=0, verbose_name='مرّات كشف الرقم')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='مرّات الحفظ')),
                ('reports_count', models.PositiveIntegerField(default=0, verbose_name='عدد البلاغات')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ النشر')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ينتهي في')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.category', verbose_name='القسم')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.neighborhood', verbose_name='الحي')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الإعلان')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='listings.listing')),
            ],
            options={
                'verbose_name': 'مفضّلة',
                'verbose_name_plural': 'المفضلة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'صورة'), ('video', 'فيديو')], default='photo', max_length=8, verbose_name='النوع')),
                ('image', models.ImageField(upload_to=apps.listings.models.media_path, verbose_name='الصورة')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=apps.listings.models.media_path, verbose_name='المصغّرة')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_main', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listings.listing', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'صورة إعلان',
                'verbose_name_plural': 'صور الإعلانات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'احتيال'), ('fake', 'إعلان مزيف'), ('violation', 'محتوى مخالف'), ('banned_item', 'منتج ممنوع'), ('other', 'سبب آخر')], max_length=16, verbose_name='السبب')),
                ('note', models.TextField(blank=True, max_length=1000, verbose_name='تفاصيل')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('resolved', 'عولج'), ('dismissed', 'مرفوض')], db_index=True, default='open', max_length=12, verbose_name='الحالة')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing', verbose_name='الإعلان')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='المُبلِّغ')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-published_at'], name='listings_li_status_477a45_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status'], name='listings_li_categor_fcaf14_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['neighborhood', 'status'], name='listings_li_neighbo_8b3825_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['user', 'status'], name='listings_li_user_id_321068_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='uniq_favorite'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('listing', 'reporter'), name='uniq_open_report_per_user'),
        ),
    ]
