# Generated by Django 5.2.17 on 2026-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_city_and_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'دولار أمريكي'), ('SYP', 'ليرة سورية'), ('TRY', 'ليرة تركية'), ('EUR', 'يورو')], db_index=True, default='USD', max_length=3, verbose_name='عملة السعر'),
        ),
    ]
