# Generated by Django 5.2.17 on 2026-08-16 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('listing_published', 'نُشر إعلانك'), ('listing_rejected', 'رُفض إعلانك'), ('listing_expiring', 'إعلانك يوشك على الانتهاء'), ('listing_expired', 'انتهى إعلانك'), ('new_pending', 'إعلان جديد بانتظار المراجعة'), ('account', 'تنبيه حساب'), ('system', 'رسالة من الإدارة')], db_index=True, max_length=24, verbose_name='النوع')),
                ('title_ar', models.CharField(max_length=140)),
                ('title_tr', models.CharField(blank=True, max_length=140)),
                ('title_en', models.CharField(blank=True, max_length=140)),
                ('body_ar', models.TextField(blank=True)),
                ('body_tr', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='مقروء')),
                ('pushed_at', models.DateTimeField(blank=True, null=True, verbose_name='أُرسل عبر FCM في')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
