# Generated by Django 5.2.17 on 2026-08-16 19:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=16)),
                ('source', models.CharField(blank=True, help_text='landing | qr | share', max_length=32)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'تنزيل',
                'verbose_name_plural': 'التنزيلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='رقم النسخة')),
                ('theme_light', models.JSONField(blank=True, default=dict, verbose_name='ألوان الوضع النهاري')),
                ('theme_dark', models.JSONField(blank=True, default=dict, verbose_name='ألوان الوضع الليلي')),
                ('font_family', models.CharField(default='Cairo', max_length=64, verbose_name='الخط')),
                ('font_scale', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.85), django.core.validators.MaxValueValidator(1.3)], verbose_name='مقياس الخط')),
                ('radius', models.JSONField(blank=True, default=dict, verbose_name='الاستدارة')),
                ('shadows', models.CharField(choices=[('flat', 'flat'), ('soft', 'soft'), ('strong', 'strong')], default='soft', max_length=12, verbose_name='الظلال')),
                ('density', models.CharField(choices=[('compact', 'compact'), ('normal', 'normal'), ('comfortable', 'comfortable')], default='normal', max_length=12, verbose_name='الكثافة')),
                ('dark_mode_enabled', models.BooleanField(default=True, verbose_name='تفعيل الوضع الليلي')),
                ('currency_code', models.CharField(default='SYP', max_length=8, verbose_name='رمز العملة')),
                ('currency_symbol', models.CharField(default='ل.س', max_length=8, verbose_name='العلامة')),
                ('currency_symbol_tr', models.CharField(blank=True, max_length=8, verbose_name='العلامة (تركي)')),
                ('currency_symbol_en', models.CharField(blank=True, max_length=8, verbose_name='العلامة (إنكليزي)')),
                ('currency_position', models.CharField(choices=[('before', 'قبل المبلغ'), ('after', 'بعد المبلغ')], default='after', max_length=8, verbose_name='موضع العلامة')),
                ('currency_decimals', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الخانات العشرية')),
                ('default_language', models.CharField(default='ar', max_length=2, verbose_name='اللغة الافتراضية')),
                ('supported_languages', models.JSONField(blank=True, default=list, verbose_name='اللغات المدعومة')),
                ('landing_ar', models.JSONField(blank=True, default=dict, verbose_name='الصفحة التعريفية (عربي)')),
                ('landing_tr', models.JSONField(blank=True, default=dict, verbose_name='الصفحة التعريفية (تركي)')),
                ('landing_en', models.JSONField(blank=True, default=dict, verbose_name='الصفحة التعريفية (إنكليزي)')),
                ('landing_image', models.ImageField(blank=True, null=True, upload_to='landing/', verbose_name='صورة الصفحة التعريفية')),
                ('apk_url', models.URLField(blank=True, verbose_name='رابط ملف APK')),
                ('apk_sha256', models.CharField(blank=True, max_length=64, verbose_name='بصمة الملف')),
                ('apk_size_mb', models.FloatField(default=0, verbose_name='حجم الملف (ميغا)')),
                ('latest_version', models.CharField(default='1.0.0', max_length=16, verbose_name='آخر إصدار')),
                ('min_version', models.CharField(default='1.0.0', max_length=16, verbose_name='أدنى إصدار مسموح')),
                ('update_message_ar', models.CharField(blank=True, max_length=200, verbose_name='رسالة التحديث (عربي)')),
                ('update_message_tr', models.CharField(blank=True, max_length=200, verbose_name='رسالة التحديث (تركي)')),
                ('update_message_en', models.CharField(blank=True, max_length=200, verbose_name='رسالة التحديث (إنكليزي)')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='المزايا')),
                ('review_mode', models.CharField(choices=[('all', 'مراجعة كل إعلان'), ('new_users', 'مراجعة إعلانات الأعضاء الجدد فقط'), ('off', 'نشر فوري بلا مراجعة')], default='all', max_length=12, verbose_name='نمط المراجعة')),
                ('review_threshold', models.PositiveSmallIntegerField(default=3, help_text='يُستخدم مع نمط «الأعضاء الجدد فقط» (plan2 §8.6)', verbose_name='عدد الإعلانات المقبولة قبل الثقة')),
                ('listing_expiry_days', models.PositiveSmallIntegerField(default=60, verbose_name='مدة صلاحية الإعلان (يوم)')),
                ('daily_listing_limit', models.PositiveSmallIntegerField(default=5, verbose_name='حد الإعلانات اليومي')),
                ('max_photos_per_listing', models.PositiveSmallIntegerField(default=10, verbose_name='أقصى عدد صور')),
                ('support_whatsapp', models.CharField(blank=True, max_length=24, verbose_name='واتساب الدعم')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الدعم')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدّل')),
            ],
            options={
                'verbose_name': 'إعدادات التطبيق',
                'verbose_name_plural': 'إعدادات التطبيق',
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'قبول إعلان'), ('reject', 'رفض إعلان'), ('suspend', 'إيقاف إعلان'), ('delete', 'حذف إعلان'), ('feature', 'تمييز إعلان'), ('user_suspend', 'إيقاف مستخدم'), ('user_ban', 'حظر مستخدم'), ('user_activate', 'تفعيل مستخدم'), ('config', 'تعديل الإعدادات'), ('report_resolve', 'معالجة بلاغ')], db_index=True, max_length=24, verbose_name='الإجراء')),
                ('target_type', models.CharField(blank=True, max_length=32, verbose_name='نوع الهدف')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الهدف')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
            ],
            options={
                'verbose_name': 'سجلّ إدارة',
                'verbose_name_plural': 'سجلّ الإدارة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_adminl_target__88eed1_idx')],
            },
        ),
    ]
