# Generated by Django 5.2.17 on 2026-08-16 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtaUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('update_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف التحديث')),
                ('runtime_version', models.CharField(db_index=True, help_text='لا تُرفع إلا عند تغيير المكتبات الأصلية', max_length=32, verbose_name='نسخة الطبقة الأصلية')),
                ('platform', models.CharField(choices=[('android', 'أندرويد'), ('ios', 'آيفون')], default='android', max_length=10, verbose_name='المنصّة')),
                ('directory', models.CharField(max_length=255, verbose_name='مجلد الحزمة')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='النشط')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تحديث عن بُعد',
                'verbose_name_plural': 'التحديثات عن بُعد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['runtime_version', 'platform', 'is_active'], name='core_otaupd_runtime_ffc337_idx')],
            },
        ),
    ]
