# Generated by Django 5.2.17 on 2026-08-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otaupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('approve', 'قبول إعلان'), ('reject', 'رفض إعلان'), ('suspend', 'إيقاف إعلان'), ('delete', 'حذف إعلان'), ('feature', 'تمييز إعلان'), ('user_suspend', 'إيقاف مستخدم'), ('user_ban', 'حظر مستخدم'), ('user_activate', 'تفعيل مستخدم'), ('user_auto_publish', 'تبديل النشر التلقائي'), ('config', 'تعديل الإعدادات'), ('report_resolve', 'معالجة بلاغ')], db_index=True, max_length=24, verbose_name='الإجراء'),
        ),
    ]
