# Generated by Django 5.2.17 on 2026-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_adminlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='app_name_ar',
            field=models.CharField(default='سوق الرقة', max_length=40, verbose_name='اسم التطبيق (عربي)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='app_name_en',
            field=models.CharField(blank=True, max_length=40, verbose_name='اسم التطبيق (إنكليزي)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='app_name_tr',
            field=models.CharField(blank=True, max_length=40, verbose_name='اسم التطبيق (تركي)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='brand_mark',
            field=models.CharField(default='س', help_text='يظهر داخل المربّع حين لا يوجد شعار مرفوع', max_length=4, verbose_name='حرف العلامة'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='launcher_icon',
            field=models.ImageField(blank=True, help_text='أيقونة الشاشة الرئيسية للجوال. تُحفظ هنا وتُطبَّق عند بناء نسخة APK التالية — أندرويد لا يسمح بتغييرها على جهاز مثبَّت', null=True, upload_to='brand/', verbose_name='أيقونة الجوال'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='يظهر في ترويسة التطبيق فورًا بلا إعادة بناء', null=True, upload_to='brand/', verbose_name='شعار التطبيق'),
        ),
    ]
