# Generated by Django 5.2.17 on 2026-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appconfig_store_url_alter_adminlog_action'),
        # حذف عملة المتجر يجب أن يأتي **بعد** نسخها إلى الإعلانات
        ('listings', '0004_backfill_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='currency_decimals',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='currency_position',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='currency_symbol_en',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='currency_symbol_tr',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='base_currency',
            field=models.CharField(default='USD', editable=False, help_text='كل أسعار الصرف تُكتب بصيغة «1 دولار = كم» — والمحور لا يُبدَّل', max_length=3, verbose_name='عملة المحور'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='default_currency',
            field=models.CharField(default='USD', help_text='ما يقرأ به المستخدم قبل أن يختار عملته', max_length=3, verbose_name='العملة الافتراضية للعرض'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='enabled_currencies',
            field=models.JSONField(blank=True, default=list, help_text='ما يظهر في قائمة العملات — فارغة تعني كل عملات الكتالوج', verbose_name='العملات المتاحة'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='rates',
            field=models.JSONField(blank=True, default=dict, help_text='«1 دولار = كم» لكل عملة. فارغ يعني: لا يُعرض تحويل تقريبي إطلاقًا', verbose_name='أسعار الصرف'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='rates_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للأسعار'),
        ),
    ]
