# Generated by Django 5.2.17 on 2026-08-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم (عربي)')),
                ('name_tr', models.CharField(blank=True, max_length=120, verbose_name='الاسم (تركي)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنكليزي)')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='المعرّف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم (عربي)')),
                ('name_tr', models.CharField(blank=True, max_length=120, verbose_name='الاسم (تركي)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنكليزي)')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='المعرّف')),
                ('icon', models.CharField(blank=True, help_text='رمز تعبيري، مثل 🚗', max_length=8, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='القسم الأب')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['sort_order', 'name_ar'],
                'indexes': [models.Index(fields=['parent', 'is_active'], name='catalog_cat_parent__e2d7e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم (عربي)')),
                ('name_tr', models.CharField(blank=True, max_length=120, verbose_name='الاسم (تركي)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنكليزي)')),
                ('slug', models.SlugField(max_length=60, verbose_name='المعرّف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='catalog.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'حي',
                'verbose_name_plural': 'الأحياء',
                'ordering': ['sort_order', 'name_ar'],
                'constraints': [models.UniqueConstraint(fields=('city', 'slug'), name='uniq_neighborhood_slug_per_city')],
            },
        ),
    ]
