# Generated by Django 5.2.17 on 2026-08-16 19:49

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('name', models.CharField(max_length=80, verbose_name='الاسم')),
                ('whatsapp_number', models.CharField(blank=True, help_text='يُترك فارغًا إن كان واتسابه على نفس رقم الحساب (plan2 §7.4)', max_length=20, verbose_name='رقم واتساب')),
                ('role', models.CharField(choices=[('user', 'مستخدم'), ('moderator', 'مشرف'), ('admin', 'مدير')], default='user', max_length=12, verbose_name='الدور')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('banned', 'محظور')], default='active', max_length=12, verbose_name='الحالة')),
                ('language', models.CharField(default='ar', max_length=2, verbose_name='اللغة')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='الهاتف موثّق')),
                ('listings_approved_count', models.PositiveIntegerField(default=0, help_text='باب الخروج من المراجعة الكاملة (plan2 §8.6)', verbose_name='عدد الإعلانات المقبولة')),
                ('suspension_reason', models.CharField(blank=True, max_length=200, verbose_name='سبب الإيقاف')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='انضمّ في')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='رمز الجهاز')),
                ('platform', models.CharField(choices=[('android', 'أندرويد'), ('ios', 'آيفون'), ('web', 'ويب')], default='android', max_length=10, verbose_name='المنصّة')),
                ('app_version', models.CharField(blank=True, max_length=16, verbose_name='إصدار التطبيق')),
                ('language', models.CharField(default='ar', max_length=2, verbose_name='اللغة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'الأجهزة',
                'ordering': ['-updated_at'],
            },
        ),
    ]
