# Generated by Django 5.2.17 on 2026-08-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_publish',
            field=models.BooleanField(db_index=True, default=False, help_text='إعلانات هذا المستخدم تُنشر فورًا بلا مراجعة — يمنحه الأدمن يدويًا', verbose_name='النشر التلقائي'),
        ),
    ]
