# Generated by Django 5.2.17 on 2026-08-19 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(db_index=True, max_length=64, verbose_name='بصمة الرقم')),
                ('reason', models.CharField(default='user_request', max_length=32, verbose_name='السبب')),
                ('listings_removed', models.PositiveIntegerField(default=0, verbose_name='إعلانات حُذفت')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'حساب محذوف',
                'verbose_name_plural': 'الحسابات المحذوفة',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL, verbose_name='المحظور')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL, verbose_name='الحاظر')),
            ],
            options={
                'verbose_name': 'حظر',
                'verbose_name_plural': 'الحظر',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='no_self_block')],
            },
        ),
    ]
